version: "3"
services:
  frontend:
    image: timssuh/docker-frontend
    #build:
    #  context: ./frontend
    #  dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    mem_limit: 128m
  nginx:
    image: timssuh/docker-nginx
    restart: always
    #build:
    #  context: ./nginx
    #  dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - frontend
      - backend
    mem_limit: 128m
  backend:
    image: timssuh/docker-backend
    #build:
    #  context: ./backend
    #  dockerfile: Dockerfile.dev
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: docker-fullstack-mysql.cqwvo3dqajbh.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: skqldi12
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
    mem_limit: 128m

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: skqldi12!@
  #     MYSQL_DATABASE: myapp
